### PR TITLE
Bump autoscaler version

### PR DESCRIPTION
**Pull request by stone-z**
Bump autoscaler version to match newest upstream for 1.15.4 release

### CODE REVIEW

**Comment by pipo02mix** [comment]
hmm but this will be released together with GS version `9.X` that will contain k8s `1.15.x`?

please ping team batman in app updates

**Comment by stone-z** [comment]
> hmm but this will be released together with GS version `9.X` that will contain k8s `1.15.x`?
Yes, will be released with 1.15 Kubernetes

**Comment by stone-z** [comment]
I have updated the PR for a new app version, but I see the kube state metrics app uses GitHub releases now for versioning. Should I do the same for this repo, or keep it the way it is?

(see this [PR](https://github.com/giantswarm/kube-state-metrics-app/pull/7) in kube state metrics)

**Review by rossf7 — APPROVED** [review]
LGTM

We haven't migrated this project to App Catalog yet. So this is the repo to change.

As its legacy it uses `appr` release channels. So in cluster-operator you'll need to bump this to `0-9-stable`.

https://github.com/giantswarm/cluster-operator/blob/5cd958e8b8dae32c1ab8d0c5f13074793dc5e5e3/service/controller/aws/v21/key/key.go#L23

**Pull request merged**
